from django.contrib import admin

# Register your models here.
from .models import Webinvestor, Project, Liquidity_Pool, Investment, Development, Venue, Liquidity, Building, Plan, Token, Guest, Information1, Information2, Hostingrules, Vaccineprotocol1, Vaccineprotocol2, Rentreduction, Tokenprogram1, Tokenprogram2, Rentopportunity, Ourcommunity1, Ourcommunity2, Development1, Overview1, Overview2, Guestrules, Costtrasparency, Guestopportunity, Reservation, Payment1, Payment2, Trading, Investorsrules, Tradingclarity, Tokenprogram3, Tradingdesk, Ourcommunity3, Report, News, Collateral, Gov, Fbm, Owner, Gin, Pro, Ten, Sub, Impressum, Vigna, Stand, Apts, Commit, Design1, Design2, Design3, Design4, Design5, Booking


admin.site.register(Webinvestor)
admin.site.register(Project)
admin.site.register(Liquidity_Pool)
admin.site.register(Investment)
admin.site.register(Development)
admin.site.register(Venue)
admin.site.register(Liquidity)
admin.site.register(Building)
admin.site.register(Plan)
admin.site.register(Token)
admin.site.register(Guest)
admin.site.register(Information1)
admin.site.register(Information2)
admin.site.register(Hostingrules)
admin.site.register(Vaccineprotocol1)
admin.site.register(Vaccineprotocol2)
admin.site.register(Rentreduction)
admin.site.register(Tokenprogram1)
admin.site.register(Tokenprogram2)
admin.site.register(Rentopportunity)
admin.site.register(Ourcommunity1)
admin.site.register(Ourcommunity2)
admin.site.register(Development1)
admin.site.register(Overview1)
admin.site.register(Overview2)
admin.site.register(Guestrules)
admin.site.register(Costtrasparency)
admin.site.register(Guestopportunity)
admin.site.register(Reservation)
admin.site.register(Payment1)
admin.site.register(Payment2)
admin.site.register(Trading)
admin.site.register(Investorsrules)
admin.site.register(Tradingclarity)
admin.site.register(Tokenprogram3)
admin.site.register(Tradingdesk)
admin.site.register(Ourcommunity3)
admin.site.register(Report)
admin.site.register(News)
admin.site.register(Collateral)
admin.site.register(Gov)
admin.site.register(Fbm)
admin.site.register(Owner)
admin.site.register(Gin)
admin.site.register(Pro)
admin.site.register(Ten)
admin.site.register(Sub)
admin.site.register(Impressum)
admin.site.register(Vigna)
admin.site.register(Stand)
admin.site.register(Apts)
admin.site.register(Commit)
admin.site.register(Design1)
admin.site.register(Design2)
admin.site.register(Design3)
admin.site.register(Design4)
admin.site.register(Design5)
admin.site.register(Booking)
