# Generated by Django 3.2.5 on 2021-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_price', models.FloatField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('dimension', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Guestroom', 'Guestroom'), ('Display area', 'Dispaly area'), ('Working station', 'Working station'), ('Office', 'Office'), ('Noursing room', 'Noursing room'), ('Food corner', 'Food corner')], max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('typology', models.CharField(max_length=200, null=True)),
                ('total_project_price', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
