# Generated by Django 3.2.5 on 2021-07-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidity_Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_project_price', models.FloatField(null=True)),
                ('liq_pool_name', models.CharField(max_length=200, null=True)),
                ('liq_pool_price', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Starting', 'Starting'), ('Filling-up', 'Filling-up'), ('Completed', 'Completed')], max_length=200, null=True)),
            ],
        ),
    ]
