# Generated by Django 3.2.5 on 2021-07-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0003_liquidity_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidity_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='co_servings.liquidity_pool')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='co_servings.project')),
            ],
        ),
    ]
