# Generated by Django 3.2.5 on 2021-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0005_investment_webinvestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='tags',
            field=models.ManyToManyField(to='co_servings.Tag'),
        ),
    ]
