# Generated by Django 3.2.5 on 2021-07-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0007_liquidity_pool_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='liquidity_pool',
            name='project',
        ),
        migrations.RemoveField(
            model_name='liquidity_pool',
            name='total_project_price',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
