# Generated by Django 3.2.5 on 2021-07-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0008_auto_20210723_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='liquidity_pool',
        ),
    ]
