# Generated by Django 3.2.5 on 2021-07-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0009_remove_investment_liquidity_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidity_pool',
            old_name='liq_pool_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='liquidity_pool',
            old_name='liq_pool_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='investment',
            name='liquidity_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='co_servings.liquidity_pool'),
        ),
    ]
