# Generated by Django 3.2.5 on 2021-07-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0010_auto_20210723_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='typology',
        ),
    ]
