# Generated by Django 3.2.5 on 2021-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0011_remove_project_typology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_description', models.TextField()),
                ('how_description', models.TextField()),
                ('users_description', models.TextField()),
            ],
        ),
    ]
