# Generated by Django 3.2.5 on 2021-08-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0016_liquidity_pool_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidity_pool',
            name='topic',
        ),
    ]
