# Generated by Django 3.2.5 on 2021-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0017_remove_liquidity_pool_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidity_pool',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
