# Generated by Django 3.2.5 on 2021-08-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0019_development'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
