# Generated by Django 3.2.5 on 2021-08-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0020_auto_20210805_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dimension',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='development',
            name='name',
        ),
    ]
