# Generated by Django 3.2.5 on 2021-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0022_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='property_price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='total_project_price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
