# Generated by Django 3.2.5 on 2021-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0023_auto_20210819_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='building',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(blank=True, choices=[('Guestroom', 'Guestroom'), ('Display area', 'Dispaly area'), ('Working station', 'Working station'), ('Office', 'Office'), ('Noursing room', 'Noursing room'), ('Food corner', 'Food corner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='property_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='total_project_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
