# Generated by Django 3.2.5 on 2021-08-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0025_liquidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidity',
            name='smart_contracts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidity',
            name='status',
            field=models.CharField(choices=[('Starting', 'Starting'), ('Filling-up', 'Filling-up'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('Guestroom', 'Guestroom'), ('Display area', 'Dispaly area'), ('Working station', 'Working station'), ('Office', 'Office'), ('Noursing room', 'Noursing room'), ('Food corner', 'Food corner')], max_length=200, null=True),
        ),
    ]
