# Generated by Django 3.2.5 on 2021-08-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0026_auto_20210821_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidity_pool',
            name='smart_contracts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
