# Generated by Django 3.2.5 on 2021-08-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0028_alter_liquidity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='plp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='projcost',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='proper',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='unit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
