# Generated by Django 3.2.5 on 2021-08-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0029_auto_20210823_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Guestroom', 'Guestroom'), ('Display area', 'Display area'), ('Working station', 'Working station'), ('Office', 'Office'), ('Noursing room', 'Nursing room'), ('Food corner', 'Food corner')], max_length=200, null=True),
        ),
    ]
