# Generated by Django 3.2.5 on 2021-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0030_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('Guestroom', 'Guestroom'), ('Display area', 'Display area'), ('Working station', 'Working station'), ('Office', 'Office'), ('Noursing room', 'Nursing room'), ('Food corner', 'Food corner')], max_length=200, null=True),
        ),
    ]
