# Generated by Django 3.2.5 on 2021-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0032_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='fbm6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
