# Generated by Django 3.2.5 on 2021-11-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0039_investorsrules_news_ourcommunity3_report_tokenprogram3_tradingclarity_tradingdesk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('ministry', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('pool', models.CharField(choices=[('Starting', 'Starting'), ('Filling_up', 'Filling_up'), ('Completed', 'Completed')], max_length=200, null=True)),
            ],
        ),
    ]
