# Generated by Django 3.2.5 on 2021-11-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0040_collateral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='collateral',
            name='pool',
            field=models.CharField(choices=[('BUSD/TIPI', 'BUSD/TIPI'), ('CAKE/TIPI', 'CAKE/TIPI'), ('ETH/TIPI', 'ETH/TIPI'), ('BNB/TIPI', 'BNB/TIPI'), ('ADA/TIPI', 'ADA/TIPI')], max_length=200, null=True),
        ),
    ]
