# Generated by Django 3.2.5 on 2021-11-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0041_auto_20211124_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateral',
            name='pool',
        ),
    ]
