# Generated by Django 3.2.5 on 2021-11-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0042_remove_collateral_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collateral',
            old_name='department',
            new_name='pool',
        ),
    ]
