# Generated by Django 3.2.5 on 2022-01-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0044_fbm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
