# Generated by Django 3.2.5 on 2022-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0046_gin_pro_sub_ten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
