# Generated by Django 3.2.5 on 2022-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0052_apts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='development',
            old_name='proper',
            new_name='Agreement_g',
        ),
        migrations.RenameField(
            model_name='development',
            old_name='unit',
            new_name='Agreement_gu',
        ),
        migrations.AddField(
            model_name='development',
            name='Agreement_i',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='Agreement_po',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='development',
            name='Agreement_t',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
