# Generated by Django 3.2.5 on 2022-04-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0053_auto_20220413_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='development',
            name='Agreement_g',
        ),
        migrations.RemoveField(
            model_name='development',
            name='Agreement_gu',
        ),
        migrations.RemoveField(
            model_name='development',
            name='Agreement_i',
        ),
        migrations.RemoveField(
            model_name='development',
            name='Agreement_po',
        ),
        migrations.RemoveField(
            model_name='development',
            name='Agreement_t',
        ),
        migrations.AddField(
            model_name='owner',
            name='Agreement_govern',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='Agreement_guest',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='Agreement_investor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='Agreement_property_owner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='Agreement_tenant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
