# Generated by Django 3.2.5 on 2022-04-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0055_auto_20220413_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('agreement_govern', models.CharField(max_length=200, null=True)),
                ('agreement_investor', models.CharField(max_length=200, null=True)),
                ('agreement_property_owner', models.CharField(max_length=200, null=True)),
                ('agreement_tenant', models.CharField(max_length=200, null=True)),
                ('agreement_guest', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
