# Generated by Django 3.2.5 on 2022-05-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0057_design1_design2_design3_design4_design5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(choices=[('1.1-milan/1', '1.1-milan/1'), ('1-florance', '1-florance/1'), ('2-berlin', '2-berlin')], max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(choices=[('fbm-2', 'fbm-2'), ('fbm-3', 'fmb-3'), ('fbm-6', 'fbm-6'), ('fbm-10', 'fbm-10'), ('fbm-16', 'fbm-16')], max_length=200, null=True)),
                ('duplex', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True)),
                ('number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=200, null=True)),
                ('starting', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
