# Generated by Django 3.2.5 on 2022-05-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0058_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='location',
            new_name='name',
        ),
    ]
