# Generated by Django 3.2.5 on 2022-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0059_rename_location_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duplex',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
