# Generated by Django 3.2.5 on 2022-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0060_auto_20220503_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='project',
            field=models.CharField(choices=[('1-milan/1', '1-milan/1'), ('1.1-florance/1', '1.1-florance/1'), ('2-berlin/1', '2-berlin/1')], max_length=200, null=True),
        ),
    ]
