# Generated by Django 3.2.5 on 2022-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0061_alter_booking_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='project',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
